#pragma once
struct Scene;
struct Mesh;
struct Model;
struct ModelNode;
struct Transform;
struct MeshRenderer;
struct Material;
struct Animator;
struct Animation;
struct AnimationChannel;
struct RigidBody;
struct Camera;
struct SpotLight;
struct PointLight;